# Generated by Django 2.2.4 on 2021-04-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='books_authors_app.Author'),
        ),
    ]
