# Generated by Django 2.2.4 on 2021-04-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_book_escritor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='escritor',
        ),
    ]
